Initialze all params at the start of the build [skip ci]
Signed-off-by: Adam Brousseau <adam.brousseau88@gmail.com>

diff --git a/buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-All b/buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-All
--- a/buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-All
+++ b/buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-All
@@ -84,10 +84,42 @@ SPECS = ['aix_ppc-64_cmprssptrs'      : CURRENT_RELEASES,
          'win_x86'                    : ['8'],
          'win_x86-64_cmprssptrs'      : CURRENT_RELEASES]
 
-LABEL = params.LABEL
-if (!LABEL) {
-    LABEL = 'worker'
-}
+// Initialize all PARAMETERS (params) to Groovy Variables even if they are not passed
+echo "Initialize all PARAMETERS..."
+LABEL = (params.LABEL) ? params.LABEL : "worker"
+echo "Setup LABEL:'${LABEL}'"
+TESTS_TARGETS = (params.TESTS_TARGETS) ? params.TESTS_TARGETS : ""
+echo "TESTS_TARGETS:'${TESTS_TARGETS}'"
+PLATFORMS = (params.PLATFORMS) ? params.PLATFORMS : ""
+echo "PLATFORMS:'${PLATFORMS}'"
+VARIABLE_FILE = (params.VARIABLE_FILE) ? params.VARIABLE_FILE : ""
+echo "VARIABLE_FILE:'${VARIABLE_FILE}'"
+VENDOR_REPO = (params.VENDOR_REPO) ? params.VENDOR_REPO : ""
+echo "VENDOR_REPO:'${VENDOR_REPO}'"
+VENDOR_BRANCH = (params.VENDOR_BRANCH) ? params.VENDOR_BRANCH : ""
+echo "VENDOR_BRANCH:'${VENDOR_BRANCH}'"
+VENDOR_CREDENTIALS_ID = (params.VENDOR_CREDENTIALS_ID) ? params.VENDOR_CREDENTIALS_ID : ""
+echo "VENDOR_CREDENTIALS_ID:'${VENDOR_CREDENTIALS_ID}'"
+PERSONAL_BUILD = (params.PERSONAL_BUILD) ? params.PERSONAL_BUILD : ""
+echo "PERSONAL_BUILD:'${PERSONAL_BUILD}'"
+BUILD_NODE_LABELS = (params.BUILD_NODE_LABELS) ? params.BUILD_NODE_LABELS : ""
+echo "BUILD_NODE_LABELS:'${BUILD_NODE_LABELS}'"
+TEST_NODE_LABELS = (params.TEST_NODE_LABELS) ? params.TEST_NODE_LABELS : ""
+echo "TEST_NODE_LABELS:'${TEST_NODE_LABELS}'"
+PROMOTE_OMR = (params.PROMOTE_OMR) ? params.PROMOTE_OMR : ""
+echo "PROMOTE_OMR:'${PROMOTE_OMR}'"
+
+// Pull Request Builds
+ghprbPullId = (params.ghprbPullId) ? params.ghprbPullId : ""
+echo "ghprbPullId:'${ghprbPullId}'"
+ghprbGhRepository = (params.ghprbGhRepository) ? params.ghprbGhRepository : ""
+echo "ghprbGhRepository:'${ghprbGhRepository}'"
+ghprbCommentBody = (params.ghprbCommentBody) ? params.ghprbCommentBody : ""
+echo "ghprbCommentBody:'${ghprbCommentBody}'"
+ghprbTargetBranch = (params.ghprbTargetBranch) ? params.ghprbTargetBranch : ""
+echo "ghprbTargetBranch:'${ghprbTargetBranch}'"
+
+VERSION_MAP = initialize_version_map()
 
 OPENJDK_REPO = [:]
 OPENJDK_BRANCH = [:]
@@ -104,10 +136,9 @@ timeout(time: 10, unit: 'HOURS') {
                 def variableFile = load 'buildenv/jenkins/common/variables-functions'
                 buildFile = load 'buildenv/jenkins/common/pipeline-functions'
 
-                VERSION_MAP = initialize_version_map()
 
                 // Determine if build is a PullRequest
-                if (params.ghprbPullId) {
+                if (ghprbPullId) {
                     // Parse Github trigger comment
                     // Jenkins test sanity <platform>*
                     // Jenkins test extended <platform>*
@@ -115,17 +146,12 @@ timeout(time: 10, unit: 'HOURS') {
                     // Jenkins test <comma_separated_test_target> <platform> *
                     //params.TESTS_TARGETS = params.ghprbCommentBody.substring(?)
                     VERSION_MAP['8'] = true
-                    echo "VERSION_MAP:'${VERSION_MAP}'"
-                    error('no')
-                    Java8 = true
-                    Java9 = false
-                    Java10 = false
-                    Java11 = false
-                    Javanext = false
-                    def newJava8Parameter = new StringParameterValue('Java8', 'true')
-                    build.replaceAction(new ParametersAction(newJava8Parameter))
                     PLATFORMS = 'linux_390-64_cmprssptrs'
+                    echo "PLATFORMS:'${PLATFORMS}'"
                     TESTS_TARGETS = 'sanity.functional'
+                    echo "TESTS_TARGETS:'${TESTS_TARGETS}'"
+                    PERSONAL_BUILD = true
+                    echo "PERSONAL_BUILD:'${PERSONAL_BUILD}'"
                 }
 
                 def BUILD_SPECS = get_specs(SPECS, VERSION_MAP)
@@ -136,7 +162,7 @@ timeout(time: 10, unit: 'HOURS') {
                 variableFile.set_job_variables('wrapper')
                 SHAS = buildFile.get_shas(OPENJDK_REPO, OPENJDK_BRANCH, OPENJ9_REPO, OPENJ9_BRANCH, OMR_REPO, OMR_BRANCH)
 
-                if (params.PERSONAL_BUILD) {
+                if (PERSONAL_BUILD) {
                     // update build name
                     wrap([$class: 'BuildUser']) {
                         currentBuild.displayName = "#${BUILD_NUMBER} - ${BUILD_USER_EMAIL}"
@@ -144,11 +170,11 @@ timeout(time: 10, unit: 'HOURS') {
 
                     // update build description
                     def TMP_DESC = (currentBuild.description) ? currentBuild.description + "<br>" : ""
-                    currentBuild.description = TMP_DESC + "<br/>${params.PLATFORMS}"
+                    currentBuild.description = TMP_DESC + "<br/>${PLATFORMS}"
                 }
 
-                def BUILD_NODES = get_node_labels(params.BUILD_NODE_LABELS, BUILD_SPECS.keySet())
-                def TEST_NODES = get_node_labels(params.TEST_NODE_LABELS, BUILD_SPECS.keySet())
+                def BUILD_NODES = get_node_labels(BUILD_NODE_LABELS, BUILD_SPECS.keySet())
+                def TEST_NODES = get_node_labels(TEST_NODE_LABELS, BUILD_SPECS.keySet())
 
                 BUILD_SPECS.each { SPEC, SDK_VERSIONS ->
                     SDK_VERSIONS.each { SDK_VERSION ->
@@ -185,7 +211,7 @@ timeout(time: 10, unit: 'HOURS') {
         // launch all pipeline builds
         parallel builds
 
-        if (params.PROMOTE_OMR) {
+        if (PROMOTE_OMR) {
             stage('Promote') {
                 PROMOTE_JOB = buildFile.build_with_slack('Promote-OpenJ9-OMR-master-to-openj9',
                                                         [string(name: 'OMR_COMMIT', value: "${SHAS['OMR']}"),
@@ -199,31 +225,6 @@ timeout(time: 10, unit: 'HOURS') {
 
 def build(OPENJDK_REPO, OPENJDK_BRANCH, SHAS, OPENJ9_REPO, OPENJ9_BRANCH, OMR_REPO, OMR_BRANCH, SPEC, SDK_VERSION, BUILD_NODE, TEST_NODE) {
     def JOB_NAME = "Adam_Pipeline-Build-Test-JDK${SDK_VERSION}-${SPEC}"
-
-    TESTS_TARGETS = (params.TESTS_TARGETS) ? params.TESTS_TARGETS : ""
-    echo "TESTS_TARGETS:'${TESTS_TARGETS}'"
-    VARIABLE_FILE = (params.VARIABLE_FILE) ? params.VARIABLE_FILE : ""
-    echo "VARIABLE_FILE:'${VARIABLE_FILE}'"
-    VENDOR_REPO = (params.VENDOR_REPO) ? params.VENDOR_REPO : ""
-    echo "VENDOR_REPO:'${VENDOR_REPO}'"
-    VENDOR_BRANCH = (params.VENDOR_BRANCH) ? params.VENDOR_BRANCH : ""
-    echo "VENDOR_BRANCH:'${VENDOR_BRANCH}'"
-    VENDOR_CREDENTIALS_ID = (params.VENDOR_CREDENTIALS_ID) ? params.VENDOR_CREDENTIALS_ID : ""
-    echo "VENDOR_CREDENTIALS_ID:'${VENDOR_CREDENTIALS_ID}'"
-    PERSONAL_BUILD = (params.PERSONAL_BUILD) ? params.PERSONAL_BUILD : ""
-    echo "PERSONAL_BUILD:'${PERSONAL_BUILD}'"
-    ghprbTargetBranch = (params.ghprbTargetBranch) ? params.ghprbTargetBranch : ""
-    echo "ghprbTargetBranch:'${ghprbTargetBranch}'"
-
-    // Pull Request Builds
-    ghprbPullId = (params.ghprbPullId) ? params.ghprbPullId : ""
-    echo "ghprbPullId:'${ghprbPullId}'"
-    ghprbGhRepository = (params.ghprbGhRepository) ? params.ghprbGhRepository : ""
-    echo "ghprbGhRepository:'${ghprbGhRepository}'"
-    ghprbCommentBody = (params.ghprbCommentBody) ? params.ghprbCommentBody : ""
-    echo "ghprbCommentBody:'${ghprbCommentBody}'"
-    ghprbTargetBranch = (params.ghprbTargetBranch) ? params.ghprbTargetBranch : ""
-    echo "ghprbTargetBranch:'${ghprbTargetBranch}'"
 
     stage ("${JOB_NAME}") {
         JOB = build job: JOB_NAME,
@@ -260,7 +261,7 @@ def build(OPENJDK_REPO, OPENJDK_BRANCH, SHAS, OPENJ9_REPO, OPENJ9_BRANCH, OMR_RE
 */
 def get_specs(SUPPORTED_SPECS, VERSION_MAP) {
     def RELEASES = []
-    def PLATFORMS = []
+    def PARSED_PLATFORMS = []
     def SPECS = [:]
 
     // get releases 
@@ -271,16 +272,16 @@ def get_specs(SUPPORTED_SPECS, VERSION_MAP) {
     }
 
     // get specs
-    if (!params.PLATFORMS || (params.PLATFORMS.trim() == 'all')) {
+    if (!PLATFORMS || (PLATFORMS.trim() == 'all')) {
         // build and test all supported specs
-        PLATFORMS.addAll(SUPPORTED_SPECS.keySet())
+        PARSED_PLATFORMS.addAll(SUPPORTED_SPECS.keySet())
     } else {
-        PLATFORMS.addAll(params.PLATFORMS.split(","))
+        PARSED_PLATFORMS.addAll(PLATFORMS.split(","))
     }
 
     def RELEASES_STR = RELEASES.join(',')
 
-    PLATFORMS.each { SPEC ->
+    PARSED_PLATFORMS.each { SPEC ->
         SPEC = SPEC.trim()
         if (!SUPPORTED_SPECS.keySet().contains(SPEC)) {
             echo "Warning: Unknown or unsupported platform: ${SPEC}"
@@ -303,14 +304,14 @@ def get_specs(SUPPORTED_SPECS, VERSION_MAP) {
     }
 
     if (!SPECS) {
-        error("Invalid PLATFORMS (${params.PLATFORMS}) and/or Java versions selections(${RELEASES_STR})!")
+        error("Invalid PLATFORMS (${PLATFORMS}) and/or Java versions selections(${RELEASES_STR})!")
     }
 
     return SPECS
 }
 
 /*
-* Returns a list of releases to build.
+* Returns a list of releases (jdk versions) to build.
 */
 def get_build_releases(BUILD_SPECS) {
     def BUILD_RELEASES = []
@@ -353,7 +354,7 @@ def get_node_labels(NODE_LABELS, SPECS) {
             }
 
             if (!SPECS.contains(ENTRY[0].trim())) {
-                error("Wrong node labels platform: ${ENTRY[0]} in ${ITEM}! It does not match any of your selected platforms: ${params.PLATFORMS}")
+                error("Wrong node labels platform: ${ENTRY[0]} in ${ITEM}! It does not match any of your selected platforms: ${PLATFORMS}")
             }
 
             LABELS.put(ENTRY[0].trim(), ENTRY[1].trim())
@@ -374,6 +375,6 @@ def initialize_version_map() {
             VERSION_MAP["${key.substring(4)}"] = value
         }
     }
-    echo "Initial VERSION_MAP:'${VERSION_MAP}"
+    echo "Initial VERSION_MAP:'${VERSION_MAP}'"
     return VERSION_MAP
 }
